version: "3"
services: 
  nginx:
    image: "nginx:1.14.2"
    container_name: "nginx1.14"
    restart: "always"
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./log:/var/log/nginx
    ports: 
      - "80:80"