version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 7017:27017
    command: [ --auth ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test
      MONGO_USERNAME: test
      MONGO_PASSWORD: test
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
